---
title: "Analisi dei dati con applicazioni informatiche"
subtitle: "Distribuzioni di Probabilità in R"
format: 
  pdf: 
   toc: true
---

\newpage

# Introduzione

Le funzioni per le distribuzioni di probabilità in R si distinguono in base all'obiettivo con cui vengono usate. La loro forma è tendenzialmente `obiettivo + distribuzione`. Ad esempio, la funzione `rnorm()` genera valori casuali (random, da cui la `r`) da una distribuzione normale (`norm`). Gli obiettivi e le lettere ad essi associati sono i seguenti: 

* `d`: funzione di densità 
* `p`: distribuzione della probabilità cumulate
* `q`: quantili della distribuzione
* `r`: valori casuali (random) estratti dalla distribuzione di riferimento

Le caratteristiche delle diverse distribuzioni (`norm`, `binom`, `t`, `chisq`, `f`), come ad esempio la media, la deviazione standard, gradi di libertà eccetera, possono essere definite tramite gli argomenti interni delle funzioni. 

# Distribuzione Binomiale

| Funzione | Descrizione |
|----------|-------------|
| `dbinom(x, size, prob)` | Restituisce i *valori di massa* associati al vettore discreto `x` di una distribuzione binomiale con `n` esperimenti bernoulliani e probabilità `prob` per l’evento target. Con `lower.tail=FALSE` calcola la probabilità complementare. |
| `pbinom(x, size, prob)` | Restituisce i *valori di probabilità cumulata* associati al vettore discreto `x`. |
| `qbinom(p, size, prob)` | Restituisce i *valori dei quantili* associati al vettore di probabilità `p`. |
| `rbinom(n, size, prob)` | Restituisce un vettore casuale di `n` osservazioni indipendenti campionate da una distribuzione binomiale. |

---

# Distribuzione Normale

| Funzione | Descrizione |
|----------|-------------|
| `dnorm(x, mean, sd)` | Restituisce i *valori di densità associati* al valore quantitativo `x` di una distribuzione normale con media e deviazione standard. |
| `pnorm(x, mean, sd)` | Restituisce i *valori di probabilità cumulata* associati al vettore `x`. |
| `qnorm(p, mean, sd)` | Restituisce i *valori dei quantili* associati al vettore di probabilità `p` di una distribuzione normale (`0 <= p <= 1`). |
| `rnorm(n, mean, sd)` | Genera un vettore casuale di `n` osservazioni indipendenti campionate da una nomrale con media e deviazione standard. |

---

# Distribuzione Chi-Quadrato

| Funzione | Descrizione |
|----------|-------------|
| `dchisq(x, df)` | Restituisce i *valori di densità* associati al vettore quantitativo `x` di una distribuzione Chi-quadrato con gradi di libertà (`df`). |
| `pchisq(x, df)` | Restituisce i *valori di probabilità cumulata* associati al vettore quantitativo `x`. |
| `qchisq(p, df)` | Restituisce i *valori dei quantili* associati al vettore di probabilità `p`. |
| `rchisq(n, df)` | Restituisce un vettore casuale di `n` osservazioni indipendenti campionate da una distribuzione chi-quadrato con `df`. |

---

# Distribuzione t di Student

| Funzione | Descrizione |
|----------|-------------|
| `dt(x, df)` | Restituisce i *valori di densità* associati al vettore quantitativo `x` di una distribuzione t con gradi di libertà (`df`). |
| `pt(x, df)` | Restituisce i *valori di probabilità cumulata* associati al vettore quantitativo `x`. |
| `qt(p, df)` | Restituisce i *valori dei quantili* associati al vettore di probabilità `p`. |
| `rt(n, df)` | Restituisce un vettore casuale di `n` osservazioni indipendenti campionate da una distribuzione t di Student con `df`. |

---

# Distribuzione F

| Funzione | Descrizione |
|----------|-------------|
| `df(x, df1, df2, ncp)` | Restituisce i *valori di densità* associati al vettore quantitativo `x` di una distribuzione F. (`ncp` = noncentrality, `df1` e `df2` = gradi di libertà). |
| `pf(x, df1, df2, ncp)` | Restituisce i *valori di probabilità cumulata* associati al vettore quantitativo `x`. |
| `qf(p, df1, df2, ncp)` | Restituisce i *valori dei quantili* associati al vettore di probabilità `p`. |
| `rf(n, df1, df2, ncp)` | Restituisce un *vettore casuale* di `n` osservazioni indipendenti campionate dall distrobuzione F. |
