---
title: "Esercitazione in Aula"
author: "Ottavia Epifania"
format: pdf
---

# Costruzione di Funzioni definite dall’utente

Si consideri la seguente struttura di dati:

```{r}
# Creazione del dataframe D
D <- data.frame(
  Genere = c("m","f","f","m","f","m","m","m","f","m",
             "f","f","f","m","f","m","f","f","m"),
  Professione = c("LP","INS","IMP","INS","LP","LP","IMP","IMP","IMP","LP",
                  "LP","LP","INS","INS","INS","LP","IMP","IMP","INS"),
  Reddito = c(65000,39000,38000,42000,22000,78000,38000,29000,39000,22000,
              42000,78000,44000,38000,36000,35000,40000,38000,37000)
)
D
```

---

## Funzione definita dall’utente

Costruiamo una funzione `SintesiReddito()` che, dato un **Genere** e una **Professione**, restituisca **media** e **deviazione standard** del reddito del sottogruppo.

```{r}
SintesiReddito <- function(DATI,ClasseG,ClasseP) {
    
    RedditoSG <- DATI$Reddito[DATI$Genere==ClasseG & DATI$Professione==ClasseP]
    MediaRSC <- mean(RedditoSG)
    DevStRSC <- sd(RedditoSG)
    OUT <- list(MEDIA=MediaRSC,DEVST=DevStRSC)
    return(OUT)

}
```

---

## Esempi di utilizzo

```{r}
# Esempio: Maschi Libero Professionista
SintesiReddito(D, "m", "LP")

# Esempio: Femmine Insegnante
SintesiReddito(D, "f", "INS")
```
